:badges:
:icons:
:toc-title: Agenda
:toc2: left
:iconsdir: http://people.redhat.com/~jduncan/images/icons
:imagesdir: images
:date: 09-Aug-2016
:location: New York, NY
:tower_url: https://ansible.tower.redhatgov.io
:toclevels: 3
:source-highlighter: highlight.js

= Automation for Everyone

.Before We Get Started
****
[.lead]
Overview

Today is meant for anyone who has any exposure to Ansible, whether you have used it or not. We are going to start with a short overview (yes, slideware) and then we'll get into the lab as soon as possible. That is where we will spend most of our time.

[.lead]
Your Responsibilities

* Have a discussion. This will be boring if it's just us up here talking for over 2 hours.
* Participate. We are going to cut you loose in a live Ansible Tower instance here in just a little while. Have questions. Have opinions.

Hopefully you have your laptop with you. If not, please find a shoulder-surfing buddy. See? Not only can we dig into Ansible but you can make a new friend!

[IMPORTANT]
.WiFi Access
====
ssid: `Red Hat Guest`

password: `atomic2016`
====
****


.Today's Team
****
[.lead]
Brad Sollar - Solutions Architect

[.lead]
Donny Davis - US Army Solutions Architect


****
== Document Copyright

This document was created by and for Red Hat, Inc. It is being released under link:https://creativecommons.org/licenses/by/4.0/[Creative Commons License 4.0]. You are free to re-use it in whole or in part.

You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.
